name: Asignar Puntos por Documentación
on:
  pull_request:
    types: [closed]

jobs:
  assign_points:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configurar Git para Commits
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Actualizar tabla de puntos
      run: |
        # Verifica si el archivo scoreboard.md existe
        if test -f scoreboard.md; then
          # Si el archivo existe, añade puntos al desarrollador
          echo "$GITHUB_ACTOR ha ganado 100 puntos" >> scoreboard.md
        else
          # Si el archivo no existe, lo crea con la tabla de puntos inicial
          echo "# Tabla de Puntuación" > scoreboard.md
          echo "| Desarrollador | Puntos |" >> scoreboard.md
          echo "|---------------|--------|" >> scoreboard.md
          echo "| $GITHUB_ACTOR | 100 |" >> scoreboard.md
        fi

    - name: Commit y Push de la tabla de puntuación
      run: |
        git add scoreboard.md
        git commit -m "Actualizar tabla de puntuación para $GITHUB_ACTOR"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

