name: Asignar Puntos por Documentación
on:
  pull_request:
    types: [closed]
jobs:
  assign_points:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Actualizar tabla de puntos
      run: |
        echo "$GITHUB_ACTOR ha completado una tarea de documentación."
        # Aquí podrías actualizar un archivo de puntuación o usar un archivo markdown
        echo "$GITHUB_ACTOR ha ganado 100 puntos por completar esta tarea."
